services:
  magi-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./.env
    command: ["uv", "run", "uvicorn", "magi.webui_backend.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/src"]
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"

  magi-frontend:
    image: node:20-alpine
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0 --port 3000"]
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - magi-backend
